p8015\_hw3\_yx2507
================

# Problem 1

load the dataset

``` r
library(p8105.datasets)
data("instacart")
```

decription of the dataset \#\# 1 How many aisles are there, and which
aisles are the most items ordered from? There are 1384617 rows and 15
columns. there are aisle, 1384617

``` r
instacart%>%
  distinct(aisle)%>%
  nrow()
```

    ## [1] 134

``` r
instacart%>% 
  count(aisle)%>%
  arrange(desc(n))
```

    ## # A tibble: 134 x 2
    ##    aisle                              n
    ##    <chr>                          <int>
    ##  1 fresh vegetables              150609
    ##  2 fresh fruits                  150473
    ##  3 packaged vegetables fruits     78493
    ##  4 yogurt                         55240
    ##  5 packaged cheese                41699
    ##  6 water seltzer sparkling water  36617
    ##  7 milk                           32644
    ##  8 chips pretzels                 31269
    ##  9 soy lactosefree                26240
    ## 10 bread                          23635
    ## # ... with 124 more rows

There are 134 distinct aisles in the dataset and the most frequently
ordered is fresh vegetables which is ordered by 150609 times. \#\# 1.2
Make a plot that shows the number of items ordered in each aisle,
limiting this to aisles with more than 10000 items ordered. Arrange
aisles sensibly, and organize your plot so others can read it.

``` r
instacart%>%
  count(aisle)%>%
  mutate(aisle = fct_reorder(aisle, desc(n)))%>%
  ggplot(aes(x = aisle, y = n))+
   scale_y_discrete(breaks = c(200000,20000, 2000, 200),labels=c("200000","20000", "2000", "200"), limits = c(10000,200000)) +
  geom_point()+
  labs(
      title = "Number of items ordered in each aisle",
      x = "Aisle",
      y = "Number of items"
    )
```

![](p8105_hw3_yx2507_files/figure-gfm/plot1-1.png)<!-- --> \#\# 1.3 Make
a table showing the three most popular items in each of the aisles
“baking ingredients”, “dog food care”, and “packaged vegetables
fruits”. Include the number of times each item is ordered in your
table.

``` r
instacart %>% 
  filter(aisle %in% c('baking ingredients', 'dog food care', 'packaged vegetables fruits')) %>% 
  group_by(aisle, product_name)  %>% 
  count() %>% 
  group_by(aisle) %>% 
  filter(n==max(n))%>%
  select(aisle, product_name)%>%
   knitr::kable(
    col.names = c("Aisle", "Most popular item"), 
    format = 'html', 
    caption = "Table: The most popular item in three aisles"
  )
```

<table>

<caption>

Table: The most popular item in three aisles

</caption>

<thead>

<tr>

<th style="text-align:left;">

Aisle

</th>

<th style="text-align:left;">

Most popular item

</th>

</tr>

</thead>

<tbody>

<tr>

<td style="text-align:left;">

baking ingredients

</td>

<td style="text-align:left;">

Light Brown Sugar

</td>

</tr>

<tr>

<td style="text-align:left;">

dog food care

</td>

<td style="text-align:left;">

Snack Sticks Chicken & Rice Recipe Dog Treats

</td>

</tr>

<tr>

<td style="text-align:left;">

packaged vegetables fruits

</td>

<td style="text-align:left;">

Organic Baby Spinach

</td>

</tr>

</tbody>

</table>
